version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: weave-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: weave
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - weave-network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weave-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/weave?authSource=admin
      JWT_SECRET: your_jwt_secret_here
      PORT: 5000
      CORS_ORIGIN: http://localhost:3000
      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret
      RAZORPAY_KEY_ID: your_razorpay_key_id
      RAZORPAY_SECRET: your_razorpay_secret
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      EMAIL_PASS: your_email_password
      SHIPROCKET_EMAIL: your_shiprocket_email
      SHIPROCKET_PASS: your_shiprocket_password
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - weave-network

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: weave-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - weave-network

volumes:
  mongodb_data:

networks:
  weave-network:
    driver: bridge 